import helpers
import llm
from prompts import blog_prompts, productivity_prompts


selected_model = "gpt-3.5-turbo"
input_text = """After peace came in 1783, the new republic faced a two-fold economic adjustment: to peacetime from the artificial production and trade patterns during the war, and to a far different trading picture than had existed before the war. The largest change between the two eras of peace was the shift in trading patterns resulting from independence. Most importantly, while Americans were freed from the shackles of British mercantilism and could trade freely with the rest of the world, the United States was now a foreign country that could no longer freely enjoy a market within the British Empire.

While the bulk of America’s trade remained with the British Empire, the pressure of New World opportunities and tightened British restrictions greatly changed the structure of American trade. American exports to Great Britain fell almost in half during the 1780s, the bulk of the drop being in rice and especially in tobacco. Before the war, tobacco was compelled to go to Britain and was re-exported from there by British merchants. Now American tobacco found other markets abroad, especially in France, where tobacco formed 70 percent of the imports from the United States. Part of this shift was impelled by a heavy English tax on foreign tobacco and rice, which lowered the British demand for American staples. Tobacco grew and prospered immediately after the Revolutionary War, particularly in the new frontier areas: Kentucky, Tennessee, and up-country South Carolina and Georgia. Virginia and other southern tobacco-growing states were initially buoyed by the high price of the crop, but by 1785 the great postwar tobacco boom was over and tobacco prices began a sharp fall.

The American naval stores—largely pitch and tar—and indigo industries had been artificially stimulated in the colonial period by British bounties; now, shorn of these subsidies, the indigo and the naval stores industries—concentrated particularly in North Carolina—declined, and their shipments were made to the northern states rather than to Great Britain. The decline of indigo, however, was offset by the rapid growth of a new southern crop: cotton, particularly in backcountry Georgia and South Carolina. Also expanding in the South was the production of grain, previously confined largely to the middle provinces. Corn, wheat, and flour production expanded greatly in the South, and Alexandria became a leading center for the export of grain.

With American-built ships now excluded from British ports, the New England shipbuilding industry, previously used by British owners and then prosperous from profiteering during the war, declined during the postwar period. The Massachusetts whaling industry, crushed during the war from loss of access to the fisheries, never really recovered due to an American shift from spermaceti to tallow candles and to prohibitory British import duties on American whale oil. The continued British military occupation of the Northwest also deprived Americans of fur trade with the Indians of that region.

While severe British restrictions diminished the British West India trade, and the Spanish West India trade was similarly cut off, smuggling helped to evade these regulations. Furthermore, American commerce expanded with the French West Indies, which furnished a ready market for American fish and wood products. Holland also greatly expanded its imports of tobacco and rice, as well as its entire trade with America. American imports of British manufactures, however, barely declined, reflecting the American consumers’ (especially the New Englanders) overwhelming preference for British goods. An additional development was America’s launching trade with Canton in China in 1784–85, in which ginseng and furs were traded for tea and calicoes. The China traders tried to get the Confederation Congress, as well as the state of Connecticut, to intervene heavily to encourage the trade, but these governments refused; one important interpenetration of politics and economics, however, was the appointment of two leading China traders, Samuel Shaw and Thomas Randall, as consuls to China—this at the instigation of John Jay, the Secretary for Foreign Affairs.

Thus, the Revolution heavily altered American foreign trade. In response, merchants expanded their partnerships to cover every major marketing center. New England shipping had been hurt by blockaded fisheries during the war but were even more stimulated by extensive profiteering. After the war, shipping declined, however, even though many Tory Boston merchants were replaced by enterprising new men moving in from smaller seaport towns in Massachusetts. The fisheries continued to be crippled since access to Newfoundland was cut off by Britain. Hence, the New England ports were not as prosperous as ports elsewhere. Newport was permanently damaged by the war and was replaced by Providence as the commercial hub of Rhode Island. The severe cutback of West India markets, moreover, crippled New England agriculture and played a large role in the chronic postwar depression of the New England farmers. In general, many coastal areas experienced consolidation of the large seaports at the expense of the smaller, e.g., Boston at the expense of smaller ports in New England, Providence replacing war-torn Newport, Hartford winning over war-ravaged New Haven, and Baltimore gaining rapidly at the expense of Annapolis. Virginia, which had never had or needed a leading port (its trade taking place on coastal rivers and wharves) created an artificial port by granting Alexandria, in 1784, a monopoly for the official entry of foreign ships. New York, devastated by occupation and war, recovered remarkably and moved to catch up to Philadelphia as the nation’s largest port.

The Revolution also produced a great (but as yet unstudied by historians) stimulus to foreign investment of capital from France and Holland that had previously been shut out by British mercantilism. French and Dutch investments were placed in American securities, currency, and commercial houses.

The slave trade, cut off during the war, resumed with the arrival of peace, especially in slave-depleted South Carolina, which imported 7,000 slaves during 1783–85. But all the states except the Carolinas and Georgia had prohibited slave imports by the end of the war, and the Carolinas followed suit in the late 1780s. Rhode Island’s gradual abolition of slavery, passed in 1784, had the effect of breaking up the large plantations of its Narragansett County, for the economic viability of these plantations had rested on slave labor. The end of slavery led to the breaking up of these quasi-feudal slave-maintained large estates and their dissolution into independent farms. The American Revolution, indeed, had an intangible—and hence neglected—but highly significant economic impact in freeing land for the market and business enterprise. The abolition of entail and primogeniture throughout the country, and especially in the South, the elimination of British proprietary estates and quitrents, the confiscation of royal forests, the redistribution of large Tory estates—all of this served to free land for flexible economic use by private enterprise. And, as Professor Ver Steeg has emphasized, the almost unnoticed abolition of Crown sovereignty over minerals and other subsoil natural resources moved these resources into the realm of free private discovery, property, and use—an event of incalculable importance for the future.1

American manufacturing in that era took place almost exclusively in homes and in small local shops; it was undertaken by self-employed artisans, or “mechanics.” It is important to realize that these mechanics were not modern proletarians, but self-employed small businessmen. The drastic reduction of imports during the war, especially from Britain, the great source of manufactured goods, stimulated an expansion of such manufacturing as textiles, salt, and iron products in the United States. It was inevitable that the end of the war should bring about a flood of British imports of which Americans had been deprived, especially textiles and all manner of specialized manufactured goods, and that much of the artificial wartime expansion would prove to be uneconomic in peacetime conditions. A readjustment of production and commerce to the new peacetime conditions had to be made, and the faster, the better. Some of the war manufacturing, notably the new iron furnaces and forges in Pennsylvania, proved to be viable, as did much of the household textile manufacturing in the South. But wartime domestic salt production was far too uneconomic to continue, and many of the manufacturers and artisans were forced to cut back in the face of the renewed competition of British and other imported goods.2"""


prompt = productivity_prompts.summarize_text_to_bullet_points.format(
    Minimum="5", Maximum="10", Text=input_text
)


# caclulate prompt cost
token_count = helpers.count_tokens(prompt, selected_model)
estmiated_cost = helpers.estimate_input_cost(selected_model, token_count)
print(f"Cost: {estmiated_cost}")


response = llm.llm_generate_text_with_save(prompt, "OpenAI", selected_model)

print("Result:")
print(response)
